config/routes.rb
Rails.application.routes.draw do
  
  get '/signup' => 'users#new', as: :sign_up
  post '/signup' => 'users#create'
  resources :users
  resources :locations
  resources :searched_locations
  resources :musics
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/spotify/playlist' => 'users#playlist', as: :spotify_playlist

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get '/auth/spotify/callback', to: 'users#spotify'

  post '/musics/most-played' => 'musics#most_played'

  get 'mysettings' => 'user_configuration#new'
  get 'mysettings/configurelastfm' => 'user_configuration#newlastfmaccountsync', as: :mysettings_configurelastfm
  patch 'mysettings/configurelastfm' => 'user_configuration#createlastfmaccountsync'
  
  get '/api/auth' => 'user_configuration#new'
  
  get 'configurationviewer' => 'users#show'
  
  get 'updateemail' => 'user_configuration#updateemail'
  
  post 'updateemail' => 'user_configuration#create'
  
  
  delete 'logout' => 'sessions#destroy'
  
  get 'changepassword' => 'user_password_config#new' 

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include LastfmHelper
  
  def index
    @spotify_musics = []
    if is_user_logged_in?
      location = Location.find_by(:user_id => session[:user_id])
      if location != nil
        # musics = Music.get_most_played(location)
        #
        # musics.each do |music|
        #   m = RSpotify::Track.search(music[0]).first
        #   @spotify_musics.push(m) unless m.nil?
        # end
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% provide(:title, 'Home') %>

<div class="row">
  <div class="col-xs-12 col-md-9">
    <input id="pac-input" class="controls" type="text" placeholder="Buscar Local">
    <div id="map"></div>
  </div>
  <div class="col-xs-12 col-md-3">
    <div id="info">
      <p>Estas são as músicas mais ouvidas desta região.</p>
    </div>
    <form action="<%= spotify_playlist_path %>" method="post">
      <input type="hidden" id="location" name="location" value="" />
      <input type="hidden" id="latitude" name="latitude" value="" />
      <input type="hidden" id="longitude" name="longitude" value="" />
      <%= token_tag %>
      <input type="submit" id="playlist" class="btn btn-primary" style="display: none" value="Gerar Playlist" />
    </form>
    <br/>
    <div id="musics">
      <p id="error"></p>
    </div>

  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxXL6ruaRsbEpHLereD5TQDEdae07fDQM&libraries=places&callback=getLocation" async defer></script>