config/routes.rb
Rails.application.routes.draw do
  
  get '/signup' => 'users#new', as: :sign_up
  post '/signup' => 'users#create'
  resources :users
  resources :locations
  resources :searched_locations
  resources :musics
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/spotify/playlist' => 'users#playlist', as: :spotify_playlist

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get '/auth/spotify/callback', to: 'users#spotify'

  post '/musics/most-played' => 'musics#most_played'

  get 'mysettings' => 'user_configuration#new'
  get 'mysettings/configurelastfm' => 'user_configuration#newlastfmaccountsync', as: :mysettings_configurelastfm
  patch 'mysettings/configurelastfm' => 'user_configuration#createlastfmaccountsync'
  
  get '/api/auth' => 'user_configuration#new'
  
  get 'configurationviewer' => 'users#show'
  
  get 'updateemail' => 'user_configuration#updateemail'
  
  post 'updateemail' => 'user_configuration#create'
  
  
  delete 'logout' => 'sessions#destroy'
  
  get 'changepassword' => 'user_password_config#new' 

  root 'welcome#index'

end

app/controllers/user_configuration_controller.rb
class UserConfigurationController < ApplicationController
    include SessionsHelper
    
  def new
    @user ||= get_current_user
  end
    
  def updateemail
    @user ||= get_current_user
    if @user.nil?
      flash[:danger] = "Por favor, faça login antes de alterar alguma configuração"
      redirect_to '/login'
    end 
  end
  
  def create

  end
  
  def newlastfmaccountsync
    @user ||= get_current_user
    redirect_when_not_logged_in
  end
  
  def createlastfmaccountsync
    @user ||= get_current_user
    @user.update_attribute(:lastfm_username, params[:user][:lastfm_username])
    redirect_to 'http://www.last.fm/api/auth/?api_key=5da1c00d06ef449b8c672b4be3ebda79&cb=' + request.base_url + mysettings_path #url_for(:only_path => false) #request.base_url #criar helper para key api
  end
  
end

app/helpers/user_configuration_helper.rb
module UserConfigurationHelper
end

app/helpers/user_configurations_helper.rb
module UserConfigurationsHelper
end

app/views/user_configuration/new.erb
<% provide(:title, 'updateemail') %>
<h1>Minhas Configurações</h1>
<!--<%= link_to 'Alterar Email', updateemail_path %>  <br/>-->
<!--<%= link_to 'Alterar Senha', changepassword_path %> <br/>-->
<%= link_to 'Sincronizar Conta LastFM', mysettings_configurelastfm_path %> <br/>
<%= link_to 'Sincronizar com Spotify', '/auth/spotify' %>

app/views/user_configuration/newlastfmaccountsync.erb
<% provide(:title, 'Conta LastFM') %>
<h1>Conta LastFM</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: mysettings_configurelastfm_path)  do |u| %>
        <%= render 'shared/error_messages' %>

        <%= u.label :lastfm_username, 'Usuário do Last.FM' %>
        <%= u.text_field :lastfm_username, class: 'form-control' %>

        <%= u.submit 'Atualizar', id: 'signup', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/user_configuration/updateemail.erb
<% provide(:title, 'updateemail') %>
<h1>Alteração de email</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:updateemail, url: updateemail_path) do |u| %>
        <%= render 'shared/error_messages' %>


        <%= u.label :current_email, 'Email atual' %>
        <%= u.email_field :current_email, class: 'form-control', :placeholder => 'Email atual' %>

        <%= u.label :future_email, 'Novo email' %>
        <%= u.email_field :future_email, class: 'form-control', :placeholder => 'Novo email' %>

        <%= u.submit 'Confirm', id: 'updateemail', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>