config/routes.rb
Rails.application.routes.draw do
  
  get '/signup' => 'users#new', as: :sign_up
  post '/signup' => 'users#create'
  resources :users
  resources :locations
  resources :searched_locations
  resources :musics
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  post '/spotify/playlist' => 'users#playlist', as: :spotify_playlist

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get '/auth/spotify/callback', to: 'users#spotify'

  post '/musics/most-played' => 'musics#most_played'

  get 'mysettings' => 'user_configuration#new'
  get 'mysettings/configurelastfm' => 'user_configuration#newlastfmaccountsync', as: :mysettings_configurelastfm
  patch 'mysettings/configurelastfm' => 'user_configuration#createlastfmaccountsync'
  
  get '/api/auth' => 'user_configuration#new'
  
  get 'configurationviewer' => 'users#show'
  
  get 'updateemail' => 'user_configuration#updateemail'
  
  post 'updateemail' => 'user_configuration#create'
  
  
  delete 'logout' => 'sessions#destroy'
  
  get 'changepassword' => 'user_password_config#new' 

  root 'welcome#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to 'Muvin', root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
            <li><%= unless is_user_logged_in?
                    link_to 'Cadastre-se', sign_up_path end%>
            </li>
            <li><%= unless is_user_logged_in?
                    link_to 'Login', login_path end%>
            </li>
            
            <li class="dropdown">
            <%= if is_user_logged_in? and session[:hash].nil?
                    link_to 'Sincronizar com Spotify', '/auth/spotify', class: "dropdown-toggle" end%>
            </li>
            
            <li><%= if is_user_logged_in?
                    link_to 'Logout', logout_path end%>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield(:title) %> | Muvin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<main class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</main>

</body>
</html>